"""invitations

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 04:38:05.030438+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.db.rls import CURRENT_INVITE_HASH_FUNCTION, enable_row_security

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_accepted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "role_id"],
            ["roles.organization_id", "roles.id"],
            name=op.f("fk_invitations_organization_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(op.f("ix_invitations_email"), "invitations", ["email"], unique=False)
    op.create_index(
        op.f("ix_invitations_organization_id"), "invitations", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_invitations_role_id"), "invitations", ["role_id"], unique=False)
    # ### end Alembic commands ###

    # Row-level security. A request sees an invitation if it is acting for that organization, OR it
    # holds the invitation's secret token (the token's hash is set for that request only).
    op.execute(CURRENT_INVITE_HASH_FUNCTION)
    for statement in enable_row_security("invitations"):
        op.execute(statement)
    mine = "(organization_id = app_current_org() OR token_hash = app_current_invite_hash())"
    op.execute(f"CREATE POLICY invitations_select ON invitations FOR SELECT USING {mine}")
    op.execute(
        "CREATE POLICY invitations_insert ON invitations FOR INSERT "
        "WITH CHECK (organization_id = app_current_org())"
    )
    op.execute(
        f"CREATE POLICY invitations_update ON invitations FOR UPDATE USING {mine} WITH CHECK {mine}"
    )
    op.execute(
        "CREATE POLICY invitations_delete ON invitations FOR DELETE "
        "USING (organization_id = app_current_org())"
    )


def downgrade() -> None:
    """Downgrade schema."""
    for policy in ("select", "insert", "update", "delete"):
        op.execute(f"DROP POLICY IF EXISTS invitations_{policy} ON invitations")
    op.execute("DROP FUNCTION app_current_invite_hash()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invitations_role_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_organization_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    # ### end Alembic commands ###
